package cn.testcross.testcrossblog.mapper;

import cn.testcross.testcrossblog.bean.ArticleTagRef;
import cn.testcross.testcrossblog.bean.ArticleTagRefExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleTagRefMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag_ref
     *
     * @mbggenerated Sun Aug 16 21:39:30 GMT+08:00 2020
     */
    int countByExample(ArticleTagRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag_ref
     *
     * @mbggenerated Sun Aug 16 21:39:30 GMT+08:00 2020
     */
    int deleteByExample(ArticleTagRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag_ref
     *
     * @mbggenerated Sun Aug 16 21:39:30 GMT+08:00 2020
     */
    int insert(ArticleTagRef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag_ref
     *
     * @mbggenerated Sun Aug 16 21:39:30 GMT+08:00 2020
     */
    int insertSelective(ArticleTagRef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag_ref
     *
     * @mbggenerated Sun Aug 16 21:39:30 GMT+08:00 2020
     */
    List<ArticleTagRef> selectByExample(ArticleTagRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag_ref
     *
     * @mbggenerated Sun Aug 16 21:39:30 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") ArticleTagRef record, @Param("example") ArticleTagRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag_ref
     *
     * @mbggenerated Sun Aug 16 21:39:30 GMT+08:00 2020
     */
    int updateByExample(@Param("record") ArticleTagRef record, @Param("example") ArticleTagRefExample example);
}