package cn.testcross.testcrossblog.mapper;

import cn.testcross.testcrossblog.bean.ArticleCategoryRef;
import cn.testcross.testcrossblog.bean.ArticleCategoryRefExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleCategoryRefMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_category_ref
     *
     * @mbggenerated Sun Aug 16 21:39:30 GMT+08:00 2020
     */
    int countByExample(ArticleCategoryRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_category_ref
     *
     * @mbggenerated Sun Aug 16 21:39:30 GMT+08:00 2020
     */
    int deleteByExample(ArticleCategoryRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_category_ref
     *
     * @mbggenerated Sun Aug 16 21:39:30 GMT+08:00 2020
     */
    int insert(ArticleCategoryRef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_category_ref
     *
     * @mbggenerated Sun Aug 16 21:39:30 GMT+08:00 2020
     */
    int insertSelective(ArticleCategoryRef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_category_ref
     *
     * @mbggenerated Sun Aug 16 21:39:30 GMT+08:00 2020
     */
    List<ArticleCategoryRef> selectByExample(ArticleCategoryRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_category_ref
     *
     * @mbggenerated Sun Aug 16 21:39:30 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") ArticleCategoryRef record, @Param("example") ArticleCategoryRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_category_ref
     *
     * @mbggenerated Sun Aug 16 21:39:30 GMT+08:00 2020
     */
    int updateByExample(@Param("record") ArticleCategoryRef record, @Param("example") ArticleCategoryRefExample example);
}