package cn.testcross.testcrossblog.mapper;

import cn.testcross.testcrossblog.bean.User;
import cn.testcross.testcrossblog.bean.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_user
     *
     * @mbggenerated Sun Aug 16 21:39:30 GMT+08:00 2020
     */
    int countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_user
     *
     * @mbggenerated Sun Aug 16 21:39:30 GMT+08:00 2020
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_user
     *
     * @mbggenerated Sun Aug 16 21:39:30 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_user
     *
     * @mbggenerated Sun Aug 16 21:39:30 GMT+08:00 2020
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_user
     *
     * @mbggenerated Sun Aug 16 21:39:30 GMT+08:00 2020
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_user
     *
     * @mbggenerated Sun Aug 16 21:39:30 GMT+08:00 2020
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_user
     *
     * @mbggenerated Sun Aug 16 21:39:30 GMT+08:00 2020
     */
    User selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_user
     *
     * @mbggenerated Sun Aug 16 21:39:30 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_user
     *
     * @mbggenerated Sun Aug 16 21:39:30 GMT+08:00 2020
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_user
     *
     * @mbggenerated Sun Aug 16 21:39:30 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc_user
     *
     * @mbggenerated Sun Aug 16 21:39:30 GMT+08:00 2020
     */
    int updateByPrimaryKey(User record);
}